//CUSTOMIZER 
export const ADD_COSTOMIZER ="ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS ="ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIXlAYOUT = "ADD_MIXlAYOUT";

//LOGIN AND COMMAN (auth)
export const SET_LOGIN_FLAG="SET_LOGIN_FLAG";
export const SET_USER_DATA="SET_USER_DATA";
export const SET_USER_AUTHTOKEN="SET_USER_AUTHTOKEN";
export const SET_ROUTE_NAME="SET_ROUTE_NAME";
export const SET_SEARCH_TEXT="SET_SEARCH_TEXT";
export const SET_SEARCH_LOADER="SET_SEARCH_LOADER";

//USER TABLE (user)
export const SET_LIST_USER_DATA="SET_LIST_USER_DATA";
export const SET_LIST_USER_DATA_TOTAL="SET_LIST_USER_DATA_TOTAL";

//Order TABLE (orders)
export const SET_LIST_ORDER_DATA="SET_LIST_ORDER_DATA";
export const SET_LIST_ORDER_DATA_TOTAL="SET_LIST_ORDER_DATA_TOTAL";
export const SET_LIST_ORDER_DATA_FLAG="SET_LIST_ORDER_DATA_FLAG";
export const SET_LIST_ORDER_DATA_REST_FLAG="SET_LIST_ORDER_DATA_REST_FLAG";

//Tag TABLE (tags)
export const SET_LIST_TAG_DATA="SET_LIST_TAG_DATA";
export const SET_LIST_TAG_DATA_TOTAL="SET_LIST_TAG_DATA_TOTAL";
export const SET_LIST_TAG_DICTIONARY="SET_LIST_TAG_DICTIONARY";

//Filter TABLE (filter)
export const SET_LIST_FILTER_DATA="SET_LIST_FILTER_DATA";
export const SET_LIST_FILTER_DATA_TOTAL="SET_LIST_FILTER_DATA_TOTAL";
export const SET_LIST_FILTER_COLUMN="SET_LIST_FILTER_COLUMN";


